import "./globals.css";
import { Inter } from "next/font/google";

import Image from "next/image";

import SideBar from "@/components/Layouts/SideBar";
import Header from "@/components/Layouts/Header";

import Background from "@/assets/image/background.png";
import HeaderSection from "@/components/HeaderSection";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex">
          <SideBar />
          <div>
            <Header />

            <div className="">
              <div
                className="w-[calc(100vw-286px)] h-full -ml-[1px]"
                style={{
                  background: `url('${Background.src}') center center`,
                }}
              >
                <HeaderSection />
                <div className="px-10 pb-16">{children}</div>
              </div>
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
