"use client";
import "./globals.css";
import { Inter } from "next/font/google";

import SideBar from "@/components/Layouts/SideBar";
import Header from "@/components/Layouts/Header";

import Background from "@/assets/image/background.png";
import { useState } from "react";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const [sideBarShow, setSideBarShow] = useState(false);

  return (
    <html lang="en">
      <head>
        {/* <!-- Primary Meta Tags --> */}
        <title>Flash Launch</title>
        <link rel="icon" type="image/x-icon" href="/logo.svg" />
        <meta name="title" content="Flash Launch" />
        <meta
          name="description"
          content="Launchpad revolutionary decentralized"
        />

        {/* <!-- Open Graph / Facebook --> */}
        <meta property="og:type" content="website" />
        <meta property="og:url" content="https://flash-launch.com/" />
        <meta property="og:title" content="Flash Launch" />
        <meta
          property="og:description"
          content="Launchpad revolutionary decentralized"
        />
        <meta property="og:image" content="/metadata.jpg" />

        {/* <!-- Twitter --> */}
        <meta property="twitter:card" content="/logo-big.png" />
        <meta property="twitter:url" content="https://flash-launch.com/" />
        <meta property="twitter:title" content="Flash Launch" />
        <meta
          property="twitter:description"
          content="Launchpad revolutionary decentralized"
        />
        <meta property="twitter:image" content="/metadata.jpg" />
      </head>
      <body className={inter.className}>
        <div className="flex max-lg:hidden">
          <SideBar mobileView={false} show={true} />
          <div>
            <Header />

            <div
              className="w-[calc(100vw-286px)] -ml-[1px] min-h-screen h-[calc(100%-80px)]"
              style={{
                background: `url('${Background.src}') center center`,
              }}
            >
              {/* <HeaderSection /> */}
              <div className="px-10 pb-16 pt-8">{children}</div>
            </div>
          </div>
        </div>
        <div className="lg:hidden">
          <SideBar
            mobileView={true}
            show={sideBarShow}
            setShow={setSideBarShow}
          />
          <div>
            <div
              className="w-[100%] h-full"
              style={{
                background: `url('${Background.src}') center center`,
              }}
            >
              <Header show={sideBarShow} setShow={setSideBarShow} />
              <div className="px-5">{children}</div>
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
